Resources:

  BucketOne:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-one-raw-data-2022-04-27

  BucketTwo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-two-converted-data-2022-04-27
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: arn:aws:lambda:eu-central-1:248461369890:function:fetch-data_write-table
  
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "author"
          AttributeType: "S"
        - AttributeName: "isbn"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "author"
          KeyType: "HASH"
        - AttributeName: "isbn"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: table-for-preferences
      StreamSpecification:
        StreamViewType: NEW_IMAGE
     
Outputs:
  DynamoStreamArn:
    Description: "Stream Arn of DynamoDB"
    Value: !GetAtt DynamoDB.StreamArn
  DynamoDBTableName:
    Value: !Ref DynamoDB
