Resources:

  ConvertedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-two-converted-data-2022-04-27
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !ImportValue FetchingLambda
  
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: table-for-preferences
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "author"
          AttributeType: "S"
        - AttributeName: "keywords"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "author"
          KeyType: "HASH"
        - AttributeName: "keywords"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    DependsOn: ConvertedDataBucket

  # EventSourceMapping:
  #   Type: AWS::Lambda::EventSourceMapping
  #   Properties:
  #     BatchSize: 300
  #     Enabled: True
  #     EventSourceArn: !GetAtt DynamoDB.StreamArn
  #     FunctionName: !ImportValue ResultsSendingLambdaFunction
  #     StartingPosition: "LATEST"
  #   DependsOn: DynamoDB

Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDB
    Export:
      Name: dbName
  DynamoStreamArn:
    Description: "Stream Arn of DynamoDB"
    Value: DynamoDB.StreamArn
    Export:
      Name: StreamDB


