Parameters:
  LambdaFunction:
    Default: python3.9
    Type: String

Resources:

  ResultsSendingLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: handle_new_titles_sns
      Role: arn:aws:iam::248461369890:role/LabRole
      Handler: handle_new_titles.lambda_sns
      Runtime: python3.9
      Timeout: 900
      Code:
          S3Bucket: !ImportValue LambdaCodeBucket
          S3Key: 'handle_new_titles.zip'
  
  ResultsSendingTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: ResultsSendingTopic
  
  TopicSubsciption:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: noraghasel@gmail.com
      Protocol: email
      TopicArn: !Ref ResultsSendingTopic
  

Outputs:
  ResultsSendingLambdaFunction:
    Description: "Arn of ResultsSendingLambdaFunction"
    Value: !GetAtt ResultsSendingLambdaFunction.Arn
    Export:
      Name: ResultsSendingLambdaFunction
