Resources:

  LambdaFunctionTwo:
    Type: AWS::Lambda::Function
    Properties: 
      Runtime: python3.9
      Role: arn:aws:iam::248461369890:role/LabRole
      Handler: handle_new_titles.lambda_sns
      FunctionName: handle_new_titles_sns
      Timeout: 900
      Code:
          S3Bucket: !ImportValue CodeBucket
          S3Key: 'handle_new_titles.zip'
  

  
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: SnsRelevantTitles

  TopicSubsciption:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: noraghasel@gmail.com
      Protocol: email
      TopicArn: !Ref SnsTopic

Outputs:
  LambdaTwoArn:
    Description: "Arn of LambdaFunctionTwo"
    Value: !GetAtt LambdaFunctionTwo.Arn
    Export:
      Name: snsLambda
