Resources:
  LambdaFunction:

    Type: AWS::Lambda::Function
    Properties: 
      Runtime: python3.9
      Role: arn:aws:iam::248461369890:role/LabRole
      Handler: code_for_zipping.lambda_handler
      FunctionName: fetch-data_write-table
      Timeout: 900
      Code:
          S3Bucket: 'lambda-code-bucket-2022-04-27'
          S3Key: 'code_for_zipping.zip'

  # CloudWatchTrigger:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties: 
  #     AlarmName: 
  #     ActionsEnabled: TRUE
  #     ComparisonOperator:

      