Parameters:
  LambdaFunction:
    Default: python3.9
    Type: String

Resources:

  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-code-bucket-2022-04-27

  DataFetchingLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: fetch-data_write-table
      Role: arn:aws:iam::248461369890:role/LabRole
      Runtime: python3.9
      Handler: code_for_zipping.lambda_handler
      Timeout: 900
      Code:
          S3Bucket: !Ref LambdaCodeBucket
          S3Key: 'code_for_zipping.zip'
    DependsOn: LambdaCodeBucket

  S3InvokeLambdaPermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref DataFetchingLambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::bucket-two-converted-data-2022-04-27

Outputs:
  DataFetchingLambdaArn:
    Description: "Arn of DataFetchingLambda"
    Value: !GetAtt DataFetchingLambdaFunction.Arn
    Export:
      Name: FetchingLambda
  LambdaCodeBucket:
    Value: !Ref LambdaCodeBucket
    Export: 
      Name: LambdaCodeBucket